# Gives the workflow a name
name: builds

# Trigger on push
on: [push, pull_request]

#
jobs:
  compiles:
    runs-on: macOS-latest
    steps: 
    - uses: actions/checkout@v1
    - run: make game1
    - run: make game2